name: Deploy (run deploy.sh)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # nur laufen, wenn Secrets gesetzt sind
    if: ${{ secrets.FTP_HOST && secrets.FTP_USER && secrets.FTP_PASS && secrets.REMOTE_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lftp jq python3

      - name: Make scripts executable
        run: chmod +x deploy.sh make_md_zip.sh make_html_zip.sh || true

      - name: Run deploy.sh (ENV-first)
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: ./deploy.sh
